# Generated by Django 4.2.6 on 2023-10-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spot_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
