# Generated by Django 4.2.6 on 2023-10-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spot_project', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_description',
            field=models.CharField(default='There is no description for this place yet', max_length=200),
        ),
    ]
