# Generated by Django 4.2.6 on 2023-10-19 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_spot_project', '0006_place_name_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name_slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_spot_project.place'),
        ),
    ]
