# Generated by Django 4.2.6 on 2023-10-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spot_project', '0007_alter_place_name_slug_alter_review_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnacceptedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('name', models.CharField(max_length=100)),
                ('place_description', models.CharField(default='There is no description for this place yet', max_length=200)),
                ('name_slug', models.SlugField(unique=True)),
            ],
        ),
    ]
