# Generated by Django 4.2.6 on 2023-11-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spot_project', '0008_unacceptedplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.DecimalField(decimal_places=14, max_digits=16),
        ),
        migrations.AlterField(
            model_name='place',
            name='long',
            field=models.DecimalField(decimal_places=14, max_digits=16),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='unacceptedplace',
            name='lat',
            field=models.DecimalField(decimal_places=14, max_digits=16),
        ),
        migrations.AlterField(
            model_name='unacceptedplace',
            name='long',
            field=models.DecimalField(decimal_places=14, max_digits=16),
        ),
        migrations.AlterField(
            model_name='unacceptedplace',
            name='place_description',
            field=models.CharField(max_length=200),
        ),
    ]
