# Generated by Django 4.2.6 on 2023-11-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spot_project', '0009_alter_place_lat_alter_place_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unacceptedplace',
            name='name_slug',
            field=models.SlugField(error_messages={'unique': 'A place with that name already exists'}, unique=True),
        ),
    ]
