# Generated by Django 4.2.6 on 2023-11-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spot_project', '0011_alter_unacceptedplace_name_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unacceptedplace',
            name='name_slug',
            field=models.SlugField(error_messages={'unique': 'This name has already been registered.'}, unique=True),
        ),
    ]
