# Generated by Django 4.2.6 on 2023-11-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spot_project', '0012_alter_unacceptedplace_name_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unacceptedplace',
            name='name',
            field=models.CharField(error_messages={'unique': 'This name has already been registered.'}, max_length=100, unique=True),
        ),
    ]
