# Generated by Django 4.2.6 on 2023-11-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spot_project', '0015_alter_place_lat_alter_place_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unacceptedplace',
            name='name',
            field=models.CharField(error_messages={'unique': 'A study spot with this name already exists (if you dont see it on the map it might not be approved yet)'}, max_length=100, unique=True),
        ),
    ]
