# Generated by Django 4.2.6 on 2023-11-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spot_project', '0019_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='average_noise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='place',
            name='average_open_seats',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='place',
            name='average_space',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
