# Generated by Django 4.2.6 on 2023-11-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_spot_project', '0021_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='has_seen_welcome_modal',
            new_name='has_seen_modal',
        ),
    ]
