# Generated by Django 4.2.6 on 2023-12-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_spot_project', '0024_unacceptedplace_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deletion_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
